import {mkdir,copyFile,writeFile,rm} from 'node:fs/promises';
import {guides} from './content.js';
const out=new URL('./dist/',import.meta.url);
await rm(out,{recursive:true,force:true});await mkdir(new URL('assets/',out),{recursive:true});
for(const [from,to] of [['../../assets/fonts/Inter-latin.woff2','inter.woff2'],['../../assets/fonts/JetBrainsMono-latin.woff2','mono.woff2'],['../../assets/fonts/LICENSE-Inter.txt','LICENSE-Inter.txt'],['../../assets/fonts/LICENSE-JetBrainsMono.txt','LICENSE-JetBrainsMono.txt'],['../../assets/brand/favicon.svg','favicon.svg'],['./style.css','style.css'],['./interactive.js','interactive.js']]) await copyFile(new URL(from,import.meta.url),new URL('assets/'+to,out));
const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const href=g=>g.slug?'/'+g.slug+'/':'/';
const anchor=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/-$/,'');
const navIcons={
 '':'M3 4h18v16H3ZM9 4v16','getting-started':'M12 3v12m-5-5 5 5 5-5M5 17v4h14v-4',workspaces:'M3 7V5h7l2 3h9v12H3Z',
 'split-view':'M3 4h18v16H3ZM12 4v16',orchestration:'m4 8 2 2 3-3M4 17l2 2 3-3M13 9h7M13 18h7',agents:'M12 3v4M12 17v4M3 12h4M17 12h4M7 7l3 3M14 14l3 3M7 17l3-3M14 10l3-3',
 browser:'M3 5h18v14H3ZM3 10h18',changes:'M7 20V5m0 0-3 3m3-3 3 3M17 4v15m0 0 3-3m-3 3-3-3',access:'M5 5h5v14H5ZM14 5h5v14h-5Z',cli:'m4 5 6 6-6 6m9 1h7',
};
const navIcon=slug=>`<svg class="nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${navIcons[slug]}"/></svg>`;
const demo=type=>`<section class="demo" data-demo="${type}" aria-label="Animated ${type} walkthrough"><div class="demo-canvas"></div><div class="film-footer"><p class="demo-caption" aria-live="off"></p><button class="film-toggle" type="button" aria-label="Pause animation">Ⅱ</button></div><div class="film-track"><div class="film-progress"></div></div><noscript><p>Read the steps below to follow this workflow.</p></noscript></section>`;
for(const [i,g] of guides.entries()){
 const nav=guides.map((n,j)=>`${j===0||n.group!==guides[j-1].group?`<p class="nav-group">${n.group}</p>`:''}<a href="${href(n)}"${n.slug===g.slug?' aria-current="page"':''}>${navIcon(n.slug)}<span>${n.nav}</span></a>`).join('');
 const body=g.sections.map(([title,copy,code])=>`<section class="prose" id="${anchor(title)}"><h2>${title}</h2><p>${copy}</p>${code?`<div class="code"><pre><code>${escape(code)}</code></pre><button type="button" class="copy" aria-label="Copy command">Copy</button><span class="copy-status" role="status"></span></div>`:''}</section>`).join('');
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(g.nav)} · Jolo documentation</title><meta name="description" content="${escape(g.intro)}"><link rel="canonical" href="https://docs.jolo.build${href(g)}"><link rel="icon" type="image/svg+xml" href="/assets/favicon.svg"><link rel="preload" href="/assets/inter.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/assets/style.css"><script defer src="/assets/interactive.js"></script></head><body><a class="skip" href="#main">Skip to content</a><header class="header"><a class="brand" href="/" aria-label="Jolo documentation home">jolo</a><span class="slash">/</span><span class="header-label">Documentation</span><nav class="external"><a href="https://github.com/jolo-build/jolo">GitHub ↗</a><a href="https://jolo.build" class="website">jolo.build ↗</a></nav><button class="menu" aria-expanded="false" aria-controls="navigation" type="button">Menu</button></header><div class="layout"><aside class="sidebar" id="navigation"><nav aria-label="Documentation">${nav}</nav><div class="sidebar-foot">Built in the open.<br><a href="https://github.com/jolo-build/jolo/issues">Suggest an improvement ↗</a></div></aside><main id="main"><div class="breadcrumb">${g.group}<span>/</span>${g.nav}</div><p class="eyebrow">THE JOLO GUIDE</p><h1>${g.title}</h1><p class="intro">${g.intro}</p>${g.demo?demo(g.demo):''}${i===0?`<div class="guide-grid"><a href="/getting-started/"><span>01 · GET STARTED</span><strong>Set up your first task ↗</strong><p>Desktop or terminal. Your choice.</p></a><a href="/orchestration/"><span>02 · GO FURTHER</span><strong>Let a plan carry the work ↗</strong><p>One goal. A sequence of agents.</p></a></div>`:''}${body}<nav class="page-links" aria-label="Guide pagination">${i>0?`<a href="${href(guides[i-1])}"><small>Previous</small>← ${guides[i-1].nav}</a>`:'<span></span>'}${i<guides.length-1?`<a href="${href(guides[i+1])}"><small>Next</small>${guides[i+1].nav} →</a>`:''}</nav><footer class="article-footer">Jolo is in active development. Controls may differ in older releases.<br><a href="https://github.com/jolo-build/jolo/releases">Check releases ↗</a></footer></main><aside class="toc"><p>On this page</p>${g.sections.map(([t])=>`<a href="#${anchor(t)}">${t}</a>`).join('')}<div class="toc-note">Learn at your pace.<br>Watch a workflow unfold. Pause whenever you need a closer look.</div></aside></div></body></html>`;
 const dir=new URL(g.slug?g.slug+'/':'',out);await mkdir(dir,{recursive:true});await writeFile(new URL('index.html',dir),html);
}
await writeFile(new URL('404.html',out),'<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Not found · Jolo</title><link rel="stylesheet" href="/assets/style.css"><main><h1>That page moved.</h1><p><a href="/">Return to the Jolo guide →</a></p></main></html>');
await writeFile(new URL('robots.txt',out),'User-agent: *\nAllow: /\nSitemap: https://docs.jolo.build/sitemap.xml\n');
await writeFile(new URL('sitemap.xml',out),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${guides.map(g=>`<url><loc>https://docs.jolo.build${href(g)}</loc></url>`).join('')}</urlset>`);
await writeFile(new URL('_headers',out),`/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self'; font-src 'self'; img-src 'self' data:; connect-src 'self'; object-src 'none'; frame-ancestors 'none'; base-uri 'none'\n`);
console.log(`Built ${guides.length} documentation pages.`);
