export const guides = [
 {slug:'',title:'Make room for your work.',nav:'Introduction',group:'Start here',intro:'One place for your coding agents, conversations, and changes. Learn Jolo by watching a workflow, then try it in your own workspace.',demo:'split',sections:[
 ['A workspace for your agents','Jolo brings a desktop app and a terminal CLI to the same local engine. Open a folder, start a task, and choose who answers: Jolo’s model harness or an installed coding agent.'],
 ['Start with a folder—or a conversation','A folder is a workspace. Each task inside it is a chat with its own history. New chat starts a conversation without choosing a project, with separate working storage for generated files.'],
 ['Learn by doing','Start with installation, then open the split-view and orchestration guides. The walkthroughs play automatically. Pause for a closer look, or follow the instructions below each one. They illustrate the interface without running real tasks.'] ]},
 {slug:'getting-started',title:'Your first task.',nav:'Installation',group:'Start here',intro:'Install the desktop app or the CLI, connect an agent, and give it a small, concrete task.',sections:[
 ['Install Jolo Desktop','Download the macOS DMG for Apple Silicon or Intel from <a href="https://jolo.build/#get-jolo">jolo.build</a>. Open it and drag Jolo into Applications. Desktop installers are currently ad-hoc signed and are not Apple-notarized.'],
 ['Install the CLI','The CLI installer includes its runtime. It does not install the desktop app. Packages are available for macOS and Linux on ARM64 and x64.', 'curl -fsSL https://jolo.build/install.sh | bash\njolo --version'],
 ['Connect an agent','Install and authenticate your preferred coding CLI separately. In Jolo, choose an agent from the composer. For the built-in agent, configure an API provider and model in Settings → Models. The demo provider is for development builds only.'],
 ['Open a folder and ask a question','Use Open folder, create a task, and start with: “Explain this repository and show me where the application starts.” Review its answer before asking for changes.', 'jolo /path/to/project'],
 ['Keep releases up to date','Newer CLI builds support jolo update --check and jolo update. If your installed version does not have that command, rerun the installer. Desktop Settings → About reports available releases; download the new DMG to update.'] ]},
 {slug:'workspaces',title:'A folder. A place to work.',nav:'Workspaces & chats',group:'Desktop',intro:'Keep project conversations together without making every conversation a project.',demo:'workspaces',sections:[
 ['Folders contain tasks','Open a folder to create a workspace. Find it under Projects in the sidebar. Expand its row to see its tasks, or open Board for an overview. Select a task to open its chat, or use the workspace’s new-task action to start another.'],
 ['Chats can stand alone','Choose New chat for a conversation outside your project folders. These chats appear under Chats in the sidebar. They keep their own history and working storage and can be opened in split view.'],
 ['Read a task at a glance','The icon beside a task shows whether it is working, finished, or needs attention. Beneath the title, Jolo shows the latest answering agent and model when available. Branch and local or worktree details identify where the work happened. Switching the composer’s agent does not rewrite that history.'],
 ['Keep tools beside the conversation','Open Panels in the upper-right corner to choose Changes, Browser, Files, Terminal, Plans, or Checks. Click Panels again to dismiss the menu. Use Hide panel to make more room for the chat; the close button belongs to the displayed panel.'],
 ['Independent conversations','Separate chats can run at the same time, even with the same agent or model. Follow-up messages queue only inside their own busy chat. Send now interrupts that chat’s current turn.'],
 ['Shared files need care','Tasks in the same folder share its files. Use a separate Git worktree when two tasks need isolated edits. Archiving a conversation removes it from the active list while keeping its history.'] ]},
 {slug:'split-view',title:'Keep both sides in view.',nav:'Split view',group:'Desktop',intro:'Bring a second conversation into the current view. Compare, follow up, and move between tasks without losing your place.',demo:'split',sections:[
 ['Drag a task into a chat','Drag a task from the sidebar or board onto the current chat. Move toward the left, right, top, or bottom edge to preview where it will open. Drop in the center to open it on the right.'],
 ['Resize your workspace','Drag the divider between panes to change their proportions. Each pane keeps its own conversation and draft. The header also offers Split right and Split below controls.'],
 ['Compare work in context','Keep a review conversation beside implementation, or compare two approaches. Split view changes what you see; it does not create a separate checkout or isolate files. Use a Git worktree for that.'] ]},
 {slug:'orchestration',title:'Turn a goal into a plan.',nav:'Orchestration',group:'Desktop',intro:'Write down the work, choose the agents, and follow each task through to its result.',demo:'orchestration',sections:[
 ['Write the plan first','Choose Panels → Plans, enter a goal, and add a task per line. Use “title: instructions” to give each task a short name and a clear brief. Review the draft before starting it.', 'Add saved searches\nExplore: Find the search UI and storage layer\nImplement: Add saved searches using existing patterns\nVerify: Run relevant checks and review the change'],
 ['Choose who does the work','A plan has a default agent. Individual tasks can carry their own agent and model choice. The plan records each task’s status and result, with a link to its conversation.'],
 ['Run one task at a time','The current orchestrator executes plan tasks sequentially in the workspace. It is not a parallel worker pool. Independent chats can still run concurrently.'],
 ['Stay in control','Pause a running plan, inspect completed work, or cancel pending work. If a task needs approval, fails, or hits a budget, the plan can wait for you. Review the issue before retrying or skipping the task.'],
 ['Resume deliberately','Plans are stored durably. After an engine restart, a previously running plan waits for your decision instead of silently starting work again.'] ]},
 {slug:'agents',title:'Choose who answers.',nav:'Agents & models',group:'Desktop',intro:'Use an installed coding agent or configure Jolo’s own model harness. Keep the choice close to the conversation.',sections:[
 ['Installed coding agents','Jolo connects to Claude Code, Codex, Grok CLI, and Gemini CLI. Install and sign in to the agent separately, then choose it in the composer. Availability depends on what is installed on the host.', 'jolo agent list\njolo run --agent claude "Explain this repository" --path /path/to/project'],
 ['Jolo’s built-in agent','Configure a supported API provider, discover its models, and select one. API keys are entered through the credential flow, not pasted into a chat.', 'jolo provider list\njolo auth set openai\njolo model list openai\njolo model set openai/<model-id>'],
 ['A model for the task','Settings → Models configures model choices. In the CLI, /model opens the selection flow. Model availability and reasoning options come from the provider or agent.'],
 ['Change perspective','Switch agents in a conversation or ask another agent for a second opinion. Conversation history supplies context; it does not transfer a vendor’s private internal state.'] ]},
 {slug:'browser',title:'The browser belongs here.',nav:'Inline browser',group:'Desktop',intro:'Keep a page next to the conversation and let your agent interact with it through Jolo’s browser tools.',demo:'browser',sections:[
 ['Open a page from chat','Ask the agent to open the inline browser and navigate to a URL. A connected desktop host provides the browser surface.', 'Open the inline browser at http://localhost:3000.\nCheck the signup form and tell me what happens after submission.'],
 ['Hide, close, and reload','Choose Panels → Browser to open the browser beside your chat. Hide panel keeps its page available. Closing the browser with its X closes that page. The browser’s reload button refreshes the page; F5 or Command-R (Control-R on Windows and Linux) reloads the desktop interface while the local engine continues running.'],
 ['Zoom the page','With the browser focused, use Command-Plus or Command-Minus on macOS, or Control-Plus and Control-Minus on Windows and Linux. Command-0 or Control-0 resets zoom. Control-wheel also zooms the inline page.'],
 ['Interact through browser tools','Supported hosted agents can navigate, inspect, click, fill forms, scroll, and capture screenshots through Jolo’s browser integration. This is browser control, not whole-computer control.'],
 ['Keep a desktop host connected','A headless CLI session alone does not supply the browser. If the agent reports that it is unavailable, check that the desktop is running, connected, and showing the relevant workspace.'],
 ['Use the right session','Pages use the workspace’s browser session. Confirm the account and destination before asking an agent to submit forms or make changes on an external service.'] ]},
 {slug:'changes',title:'From an edit to confidence.',nav:'Changes & approvals',group:'Desktop',intro:'Read what changed, follow the checks, and give permission when a task needs your decision.',demo:'review',sections:[
 ['Review the diff','Choose Panels → Changes to inspect the files changed in the workspace. Ask the agent to explain the intent, relevant tests, and remaining limitations. You can revert individual agent edits when needed.'],
 ['Keep checks and the terminal close','Choose Panels → Checks to inspect verification results, or Panels → Terminal to use the workspace shell. Switching panels preserves the terminal session and plan state.'],
 ['Understand an approval','When Jolo asks permission, review the command, target, and scope before allowing it. A paused task needs a decision; it is not necessarily a failed run.'],
 ['Separate edits with worktrees','A Git worktree gives a task its own checkout. Use it for changes that should not collide with work already in your main folder. A split pane alone does not provide this isolation.'],
 ['Preview generated explanations','HTML visualizations can render in conversation and expand for a closer look. They are sandboxed and loaded from the conversation’s own workspace. The CLI shows a readable file reference.'] ]},
 {slug:'access',title:'Keep the team in the loop.',nav:'Access web tasks',group:'Connected work',intro:'Use the web platform for tasks, comments, teams, and labels. Connect local work when you need an agent to act.',sections:[
 ['Sign in to Access','Open <a href="https://access.jolo.build">access.jolo.build</a> and use an available sign-in option. Local coding does not require an Access account.'],
 ['Choose the task’s workspace','Create a personal task or select a team workspace. Add a title, description, priority, assignee, and labels. Available assignees and labels depend on the selected workspace and your permissions.'],
 ['Give your team a ticket prefix','When creating a team, choose a unique prefix such as JOLO or leave it blank for Jolo to choose. Use 2–24 letters or digits, starting with a letter. Personal accounts receive their own prefix automatically. Each workspace counts independently: JOLO-1, JOLO-2, and TEAM-1, TEAM-2. Renaming the team keeps its prefix and existing ticket IDs.'],
 ['Discuss the work','Open a task to read its description and comments. The conversation scrolls while the task header and comment composer stay accessible. You can edit your own comments.'],
 ['Bring a task into a local conversation','Sign in with task access and open the correct local project. Type # and choose a task from the picker, or write its full key directly, such as #JOLO-2. Jolo finds the workspace from the prefix and checks your access before attaching the task. Full Access URLs also work.', '@codex #JOLO-123 investigate this issue, implement a fix, and run the relevant tests'],
 ['A web task is not a remote runner','Access manages identity and task records. Coding commands execute on the connected runner or local host. Opening a web task does not by itself start a cloud coding environment.'] ]},
 {slug:'cli',title:'At home in your terminal.',nav:'CLI reference',group:'Connected work',intro:'Start a conversation, run a focused headless task, or inspect the engine from the command line.',sections:[
 ['Interactive mode','Open a folder in Jolo. Enter sends a prompt, Esc stops active work, Tab reveals tool output, /sessions opens saved conversations, and /model changes the answerer.', 'jolo /path/to/project'],
 ['Headless runs','Supply a prompt and agent to run without the interactive interface. Add --json on supported commands when integrating structured results.', 'jolo run --agent claude "Review the latest changes" --path /path/to/project\njolo --help'],
 ['Profiles and engine lifetime','The local engine starts automatically and may outlive a client. Use --home and --profile for separate state. Finish active tasks before stopping the engine.', 'jolo engine stop'],
 ['Exit codes','0: success. 1: failure. 2: usage error. 3: permission pause. 4: budget pause. 5: another pause. 130: cancellation. Handle pauses as requests for attention rather than blindly retrying.'],
 ['More command details','The <a href="https://github.com/jolo-build/jolo/blob/main/apps/cli/README.md">CLI README</a> covers provider configuration, updates, profiles, and removal. Run jolo --help for the commands supported by your installed version.'] ]},
];
