import { randomBytes } from "node:crypto";
export const newId = (prefix) => `${prefix}_${randomBytes(9).toString("base64url")}`;
export const now = () => new Date().toISOString();

export const mapSession = (r) => r && ({ id: r.id, projectId: r.project_id, workspaceId: r.workspace_id, title: r.title, revision: r.revision, state: r.state, agentId: r.agent_id ?? null, planTaskId: r.plan_task_id ?? null, model: r.model_ref ? JSON.parse(r.model_ref) : null, agentState: r.agent_state ? JSON.parse(r.agent_state) : {}, createdAt: r.created_at, updatedAt: r.updated_at });
export const mapPlan = (r) => r && ({ id: r.id, projectId: r.project_id, workspaceId: r.workspace_id, goal: r.goal, state: r.state, policy: r.policy ? JSON.parse(r.policy) : {}, revision: r.revision, failure: r.failure ?? null, createdAt: r.created_at, updatedAt: r.updated_at });
export const mapPlanTask = (r) => r && ({ id: r.id, planId: r.plan_id, position: r.position, title: r.title, brief: r.brief, agentId: r.agent_id ?? null, model: r.model ?? null, effort: r.effort ?? null, state: r.state, blockedReason: r.blocked_reason ?? null, revision: r.revision, sessionId: r.session_id ?? null, acceptedExecutionId: r.accepted_execution_id ?? null, summary: r.summary ?? null, createdAt: r.created_at, updatedAt: r.updated_at });
export const mapPlanExecution = (r) => r && ({ id: r.id, planId: r.plan_id, taskId: r.task_id, attempt: r.attempt, purpose: r.purpose, runId: r.run_id ?? null, sessionId: r.session_id ?? null, agentId: r.agent_id ?? null, model: r.model ?? null, effort: r.effort ?? null, outcome: r.outcome ?? null, detail: r.detail ?? null, usage: r.usage ? JSON.parse(r.usage) : {}, startedAt: r.started_at, endedAt: r.ended_at ?? null });
export const mapRun = (r) => r && ({ id: r.id, sessionId: r.session_id, requestId: r.request_id, attempt: r.attempt, state: r.state, revision: r.revision, prompt: r.prompt, attachments: r.attachments ? JSON.parse(r.attachments) : [], execution: r.execution ? JSON.parse(r.execution) : null, pauseReason: r.pause_reason ?? null, failure: r.failure ?? null, verification: r.verification ? JSON.parse(r.verification) : null, usage: r.usage ? JSON.parse(r.usage) : {}, note: r.note ? JSON.parse(r.note) : null, createdAt: r.created_at, updatedAt: r.updated_at });
export const mapProject = (r) => r && ({ id: r.id, identity: r.identity, rootPath: r.root_path, preferences: r.preferences ? JSON.parse(r.preferences) : {}, createdAt: r.created_at, updatedAt: r.updated_at });
export const mapPermission = (r) => r && ({ id: r.id, runId: r.run_id, sessionId: r.session_id, workspaceId: r.workspace_id, tool: r.tool, request: JSON.parse(r.request), state: r.state, decision: r.decision ?? null, grantId: r.grant_id ?? null, revision: r.revision, createdAt: r.created_at, resolvedAt: r.resolved_at ?? null });
export const mapMessage = (r) => r && ({ id: r.id, sessionId: r.session_id, runId: r.run_id ?? null, ordinal: r.ordinal, role: r.role, kind: r.kind ?? "text", artifactId: r.artifact_id, committedBytes: r.committed_bytes, status: r.status });
export const mapItem = (r) => r && ({ id: r.id, sessionId: r.session_id, runId: r.run_id ?? null, ordinal: r.ordinal, kind: r.kind, groupId: r.group_id, messageId: r.message_id ?? null, invocationId: r.invocation_id ?? null, payload: JSON.parse(r.payload), createdAt: r.created_at });
export const mapInvocation = (r) => r && ({ id: r.id, runId: r.run_id, providerCallId: r.provider_call_id ?? null, name: r.name, argumentDigest: r.argument_digest, grantId: r.grant_id ?? null, state: r.state, exitData: r.exit_data ? JSON.parse(r.exit_data) : null, resultArtifactId: r.result_artifact_id ?? null, createdAt: r.created_at, updatedAt: r.updated_at });
export const mapGrant = (r) => r && ({ id: r.id, scope: r.scope, constraints: JSON.parse(r.constraints), expiresAt: r.expires_at ?? null, policyRevision: r.policy_revision, createdAt: r.created_at });
export const mapWorkspace = (r) => r && ({ id: r.id, projectId: r.project_id, mode: r.mode, path: r.path, branch: r.branch ?? null, baseCommit: r.base_commit ?? null, owned: Boolean(r.owned), lastViewedAt: r.last_viewed_at ?? null, removedAt: r.removed_at ?? null, createdAt: r.created_at });
export const mapArtifact = (r) => r && ({ id: r.id, sessionId: r.session_id, kind: r.kind, storageKey: r.storage_key, committedBytes: r.committed_bytes, finalizedHash: r.finalized_hash ?? null, retentionClass: r.retention_class, createdAt: r.created_at });
