# Generated by scripts/update-homebrew-tap.js — edit the script, not this file.
class JoloCli < Formula
  desc "Terminal CLI for working with coding agents"
  homepage "https://jolo.build"
  version "0.2.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/jolo-build/jolo/releases/download/v#{version}/jolo-cli-darwin-arm64.tar.gz"
      sha256 "c4061dc3c86ae30b72d4423fba3236874b5d910e5f524da50fba72f37c604b6d"
    end
    on_intel do
      url "https://github.com/jolo-build/jolo/releases/download/v#{version}/jolo-cli-darwin-x64.tar.gz"
      sha256 "636ec636a898da396a7e49fb0127ae9e8e7b9e9c2aabffaaf8083e70f450c990"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/jolo-build/jolo/releases/download/v#{version}/jolo-cli-linux-arm64.tar.gz"
      sha256 "fe22968f694ecb7dca6555f3e347d2c06d731991bfdee3636d5c965fb19fb7fb"
    end
    on_intel do
      url "https://github.com/jolo-build/jolo/releases/download/v#{version}/jolo-cli-linux-x64.tar.gz"
      sha256 "ec6f2ef2999f5a238b57c6fae33ac4c5f183eeeff0b61eb9b286792efaff1791"
    end
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"bin/jolo"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jolo --version")
  end
end
