# Generated by scripts/update-homebrew-tap.js — edit the script, not this file.
cask "jolo" do
  version "0.2.1"

  arch arm: "arm64", intel: "x64"

  sha256 arm:   "b3be75b6056580aa26545b6bcbc2a7f086549110fe3095889fe94d6fbeaeac0f",
         intel: "7c26c043b0db2b824b9639994e5769dd63c107fa845aec2bb084e6267891f593"

  url "https://github.com/jolo-build/jolo/releases/download/v#{version}/jolo-desktop-darwin-#{arch}.dmg"
  name "Jolo"
  desc "Desktop app for working with coding agents"
  homepage "https://jolo.build"

  app "Jolo.app"

  zap trash: [
    "~/Library/Application Support/Jolo",
    "~/Library/Caches/jolo",
    "~/Library/Preferences/dev.jolo.desktop.plist",
    "~/Library/Saved Application State/dev.jolo.desktop.savedState",
  ]
end
